apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "rest-api"
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
    github.com/project-slug: "shiftdp/rest-api"
  links:
    - url: 'https://rest-api-service-uzl2sxzu2q-oc.a.run.app'
      title: '"rest-api" Link'
      # icon: ''
      # type: ''
spec:
  type: service
  owner: user:fasanosalvatore
  lifecycle: experimental
