apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo
  description: System for demo purposes
spec:
  owner: user:fasanosalvatore
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rest-api-registry
  description: Docker Registry
spec:
  type: registry
  owner: user:fasanosalvatore
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "rest-api"
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
    github.com/project-slug: "shiftdp/rest-api"
  links:
    - url: 'https://rest-api-service-uzl2sxzu2q-oc.a.run.app'
      title: '"rest-api" Link'
      # icon: ''
      # type: ''
spec:
  system: demo
  type: service
  owner: user:fasanosalvatore
  lifecycle: production
  dependsOn:
    - rest-api-registry
